### ISSUE TITLE
Is it possible to compiled with SYCL?

### ISSUE THREAD

**Issue by FrankZhong921** [Im-Rises/CMake-Cpp-Library-Example#11]
I notice there is opencl version. Is it possible to compiled with SYCL? or any plan to do it?

**Comment by Im-Rises** [comment]
Hello, sorry for the delay in answering. I don't know never try, I'll update you this week-end if you didn't aready find out ;)

**Comment by Im-Rises** [comment]
I tested, it seems they can run together. Did you try?
